Document: ppmsens
Title: Debian ppmsens Manual
Author: <insert document author here>
Abstract: This manual describes what ppmsens is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ppmsens/ppmsens.sgml.gz

Format: postscript
Files: /usr/share/doc/ppmsens/ppmsens.ps.gz

Format: text
Files: /usr/share/doc/ppmsens/ppmsens.text.gz

Format: HTML
Index: /usr/share/doc/ppmsens/html/index.html
Files: /usr/share/doc/ppmsens/html/*.html
