#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.1.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'tasmonitor.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p tasmonitor 
else
	dpkg -L tasmonitor | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
