Document: co2sens
Title: Debian co2sens Manual
Author: <insert document author here>
Abstract: This manual describes what co2sens is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/co2sens/co2sens.sgml.gz

Format: postscript
Files: /usr/share/doc/co2sens/co2sens.ps.gz

Format: text
Files: /usr/share/doc/co2sens/co2sens.text.gz

Format: HTML
Index: /usr/share/doc/co2sens/html/index.html
Files: /usr/share/doc/co2sens/html/*.html
